// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentvariables.proxies;

public class EnvironmentVariables
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject environmentVariablesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EnvironmentVariables.EnvironmentVariables";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Letter("Letter");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EnvironmentVariables(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EnvironmentVariables.EnvironmentVariables"));
	}

	protected EnvironmentVariables(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject environmentVariablesMendixObject)
	{
		if (environmentVariablesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EnvironmentVariables.EnvironmentVariables", environmentVariablesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EnvironmentVariables.EnvironmentVariables");

		this.environmentVariablesMendixObject = environmentVariablesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EnvironmentVariables.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static environmentvariables.proxies.EnvironmentVariables initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return environmentvariables.proxies.EnvironmentVariables.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static environmentvariables.proxies.EnvironmentVariables initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new environmentvariables.proxies.EnvironmentVariables(context, mendixObject);
	}

	public static environmentvariables.proxies.EnvironmentVariables load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return environmentvariables.proxies.EnvironmentVariables.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Letter
	 */
	public final java.lang.String getLetter()
	{
		return getLetter(getContext());
	}

	/**
	 * @param context
	 * @return value of Letter
	 */
	public final java.lang.String getLetter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Letter.toString());
	}

	/**
	 * Set value of Letter
	 * @param letter
	 */
	public final void setLetter(java.lang.String letter)
	{
		setLetter(getContext(), letter);
	}

	/**
	 * Set value of Letter
	 * @param context
	 * @param letter
	 */
	public final void setLetter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String letter)
	{
		getMendixObject().setValue(context, MemberNames.Letter.toString(), letter);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return environmentVariablesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final environmentvariables.proxies.EnvironmentVariables that = (environmentvariables.proxies.EnvironmentVariables) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EnvironmentVariables.EnvironmentVariables";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
