// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentvariables.proxies;

/**
 * Per EnvironmentType define the text that will be part of the environment's url. 
 * If left blank, then during startup it will get filled with 
 * T, -test., empty
 * A, -accp., empty
 * P, .mendixcloud.com, empty
 * 
 * D is not needed since checking the url against D is done via commcomm's widget IsDevelopment
 */
public class TAPUrlText
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tAPUrlTextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EnvironmentVariables.TAPUrlText";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EnvironmentType("EnvironmentType"),
		PartOfUrl("PartOfUrl"),
		Url("Url");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TAPUrlText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EnvironmentVariables.TAPUrlText"));
	}

	protected TAPUrlText(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tAPUrlTextMendixObject)
	{
		if (tAPUrlTextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EnvironmentVariables.TAPUrlText", tAPUrlTextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EnvironmentVariables.TAPUrlText");

		this.tAPUrlTextMendixObject = tAPUrlTextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TAPUrlText.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static environmentvariables.proxies.TAPUrlText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return environmentvariables.proxies.TAPUrlText.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static environmentvariables.proxies.TAPUrlText initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new environmentvariables.proxies.TAPUrlText(context, mendixObject);
	}

	public static environmentvariables.proxies.TAPUrlText load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return environmentvariables.proxies.TAPUrlText.initialize(context, mendixObject);
	}

	public static java.util.List<environmentvariables.proxies.TAPUrlText> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<environmentvariables.proxies.TAPUrlText> result = new java.util.ArrayList<environmentvariables.proxies.TAPUrlText>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EnvironmentVariables.TAPUrlText" + xpathConstraint))
			result.add(environmentvariables.proxies.TAPUrlText.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of EnvironmentType
	 * @param environmenttype
	 */
	public final environmentvariables.proxies.Enum_EnvironmentType getEnvironmentType()
	{
		return getEnvironmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EnvironmentType
	 */
	public final environmentvariables.proxies.Enum_EnvironmentType getEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnvironmentType.toString());
		if (obj == null)
			return null;

		return environmentvariables.proxies.Enum_EnvironmentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnvironmentType
	 * @param environmenttype
	 */
	public final void setEnvironmentType(environmentvariables.proxies.Enum_EnvironmentType environmenttype)
	{
		setEnvironmentType(getContext(), environmenttype);
	}

	/**
	 * Set value of EnvironmentType
	 * @param context
	 * @param environmenttype
	 */
	public final void setEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context, environmentvariables.proxies.Enum_EnvironmentType environmenttype)
	{
		if (environmenttype != null)
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), environmenttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), null);
	}

	/**
	 * @return value of PartOfUrl
	 */
	public final java.lang.String getPartOfUrl()
	{
		return getPartOfUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of PartOfUrl
	 */
	public final java.lang.String getPartOfUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartOfUrl.toString());
	}

	/**
	 * Set value of PartOfUrl
	 * @param partofurl
	 */
	public final void setPartOfUrl(java.lang.String partofurl)
	{
		setPartOfUrl(getContext(), partofurl);
	}

	/**
	 * Set value of PartOfUrl
	 * @param context
	 * @param partofurl
	 */
	public final void setPartOfUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partofurl)
	{
		getMendixObject().setValue(context, MemberNames.PartOfUrl.toString(), partofurl);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tAPUrlTextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final environmentvariables.proxies.TAPUrlText that = (environmentvariables.proxies.TAPUrlText) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EnvironmentVariables.TAPUrlText";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
