// This file was generated by Mendix Modeler 7.1.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package environmentvariables.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the EnvironmentVariables module

	/**
	* Either D, T, A or P and limited to those four values.
	* Default is D because this is usefull during development.
	*/
	public static java.lang.String getEnvironmentLetter()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EnvironmentVariables.EnvironmentLetter");
	}

	public static java.lang.String getLognode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EnvironmentVariables.Lognode");
	}
}